<?php

declare(strict_types=1);
class Link_Presenter_Test extends \PHPUnit\Framework\TestCase
{
  public function setUp(): void
  {
    require_once __DIR__ . '/../link_presenter.php';
    parent::setUp(); // TODO: Change the autogenerated stub
  }

  public function test_can_generate_link_from_array()
  {
    $example_link_array_1 = [
      'id' => 1,
      'url' => 'https://www.linkedin.com',
    ];

    $url = generate_link_from_array($example_link_array_1);
    $this->assertEquals('https://www.linkedin.com', $url);

    $example_link_array_2 = [
      'id' => false,
      'url' => 'learning',
    ];
    $url = generate_link_from_array($example_link_array_2);
    $this->assertEquals('https://www.linkedin.com/learning', $url);

  }

  public function test_create_url()
  {
    $example_link_array_1 = [
      'id' => false,
      'url' => 'https://www.linkedin.com',
    ];

    $url = generate_link_from_array($example_link_array_1);
    $this->assertEquals('https://www.linkedin.com', $url);
  }


}
